service:
  enabled: true
  single: true
  type: LoadBalancer

additionalArguments:
- "--api.insecure=true"

ingressRoute:
  dashboard:
    enabled: true
    # Custom match rule with host domain
    matchRule: Host(`localhost`)
    entryPoints: ["web"]

ports:
  traefik:
    expose:
      default: true

deployment:
  dnsPolicy: ClusterFirstWithHostNet

hostNetwork: true