---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: istio-upstream
  namespace: ambassador
spec:
  secret: istio-system.istio-ca-secret
  secret_namespacing: false
  alpn_protocols: istio
