apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - image: docker.io/dallinpm/hello-world
          env:
            - name: TARGET
              value: "Python Sample v1"
