apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - image: docker.io/dallinpm/hello-world
          env:
            - name: TARGET
              value: "Python Sample v1"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
  namespace: istio-ingress
spec:
  hosts:
    - hello-world.example.com
  gateways:
    - knative-gateway # Replace with your actual gateway name
  http:
    - route:
        - destination:
            host: hello-world.services.svc.cluster.local
            weight: 100
