apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  namespace: services
spec:
  template:
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - image: ghcr.io/dallinwright/kubernetes-quickstart
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Python Sample v1"
