apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-credentials
  namespace: grafana
type: Opaque
data:
  prometheus_host: ""
  prometheus_username: ""
  loki_host: ""
  loki_username: ""
  tempo_host: ""
  tempo_username: ""
  grafana_password: ""
