cluster:
  name: Dallin Wright's Development Cluster

externalServices:
  prometheus:
    hostKey: prometheus_host
    basicAuth:
      usernameKey: prometheus_username
      passwordKey: grafana_password
    secret:
      create: false
      name: grafana-agent-credentials

  loki:
    hostKey: loki_host
    basicAuth:
      usernameKey: loki_username
      passwordKey: grafana_password
    secret:
      create: false
      name: grafana-agent-credentials

  tempo:
    hostKey: tempo_host
    basicAuth:
      usernameKey: tempo_username
      passwordKey: grafana_password
    secret:
      create: false
      name: grafana-agent-credentials

metrics:
  enabled: true
  scrapeInterval: 15s
  cost:
    enabled: false
  node-exporter:
    enabled: true

logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true

traces:
  enabled: true

receivers:
  grpc:
    enabled: true
  http:
    enabled: true

opencost:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-operator-crds:
  enabled: true

grafana-agent: { }

grafana-agent-logs: { }
