apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  annotations:
    # This annotation is required for the Knative Serving controller to
    # be able to manage the Istio resources.
    # The value must be the namespace where Istio is installed.
    # If Istio is installed in the same namespace as Knative Serving,
    # this annotation is not needed.
    # If Istio is not installed, this annotation should be removed.
    networking.istio.io/rev: default
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  config:
    istio:
      local-gateway.<local-gateway-namespace>.knative-local-gateway: "knative-local-gateway.<istio-namespace>.svc.cluster.local"